apiVersion: v1
kind: Template
metadata:
  name: ali-aboud-kafka-build
  annotations:
    description: Kafkanetes builder
    iconClass: fa-database
    tags: bigdata,aliaboud,messaging,kafka,zookeeper

parameters:
- name: SOURCE_REPOSITORY_URL
  description: The URL of the Git repository with the Kafkanetes Dockerfile
  required: true
  value: https://github.com/aliaboud/kafkanetes.git
- name: OBJECT_NAME_PREFIX
  description: Name prefix for each object created
  required: true
  value: aliaboudkafka

objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${OBJECT_NAME_PREFIX}

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    strategy:
      type: Docker
    source:
      type: Git
      git:
        uri: ${SOURCE_REPOSITORY_URL}
    output:
      to:
        kind: ImageStream
        name: ${OBJECT_NAME_PREFIX}
    triggers:
    - type: ConfigChange
